version: '3.7'

services:

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: bd-pass-in
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRESS_USER}
      - POSTGRES_PASSWORD=${POSTGRESS_PASSWORD}
      - POSTGRES_DB=${POSTGRESS_DB}
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - passin

  api-pass-in:
    build:
      context: .
    container_name: api-pass-in
    ports:
      - 3001:3333
    environment:
      - DATABASE_URL=postgresql://${POSTGRESS_USER}:${POSTGRESS_PASSWORD}@postgres:5432/${POSTGRESS_DB}
      - API_BASE_URL=http://localhost:3333
    depends_on:
      - postgres
    networks:
      - passin

networks:
  passin:
    driver: bridge

volumes:
  db: